### ISSUE TITLE
Small images on Contact page show large

### ISSUE THREAD

**Issue by solitudeape** [victoras/charitas-lite#15]
I have a series of small images that are 'partners' with this organization, linked to other site. Each is uniformly 50px high on the contact page - http://alalusi.timscottphotography.com/contact-us/ - but when viewed live, they are huge. I've looked through settings and can't make sense of this.

![screen shot 2017-05-30 at 7 37 25 pm](https://cloud.githubusercontent.com/assets/29083466/26613454/ac67d41a-456f-11e7-8f23-4ed2757abfa8.png)

**Comment by victoras** [comment]
Hi, Can you set the alignment to left for every image? The same when you set it you can choose the size, make sure you added the right size. Let us know if the solutions work for you.

**Comment by solitudeape** [comment]
Yep. That took care of the problem. Interesting. They were all aligned right.

Thank you.

**Comment by victoras** [comment]
You are welcome! Don't forget to give a 5 Star rating to the theme! Thanks!
