### ISSUE TITLE
home page widget areas

### ISSUE THREAD

**Issue by tabithastapely** [victoras/charitas-lite#7]
I have recently uploaded Charitas Lite onto my Wordpress.org website, www.romanroadrba.co.uk. 

Under the Appearance>Widgets section of the Wordpress.org dashboard there are four home page widget areas that can be edited. However done of them seem to be working. Is this correct?

There are four footer widget areas that are editable so it seems strange that there are no home page widget areas at all, even for a free theme.

As I cannot edit the home page areas at all, the Latest Posts section is populating with endless posts as I cannot control the amount of posts being displayed. This is causing a very (endlessly?) long home page.

So, can I get the home page widget areas to work? If so, how? If not, how can I at least cap the number of posts being displayed in the Latest Post area of the home page?

Kind regards, Tabitha

**Comment by victoras** [comment]
Hi,

You have to chose a Static Front Page like in the attached image. When you add the home page make sure you chose the right template from page attribute.

<img width="381" alt="screenshot 2015-08-09 23 46 05" src="https://cloud.githubusercontent.com/assets/613284/9159141/d766faf6-3ef0-11e5-8dc3-e9e28c9dcd18.png">

**Comment by tabithastapely** [comment]
Thanks Victor. I have done this but am I have now lost the Home Page splash. In fact the Home Page seems to lose all differentiation from a Page with the same widgets that the Pages have.

 Also, I still can't get any widgets to appear in the Home Page area. I have dragged Latest Posts widget into the First Home Page Area but nothing appears on the Home Page when I Save and Publish.

The only way I can effect the Home Page is adding widgets either to Page Posts Area (when Home Page in Static mode) or to Press/Blog Area (when Home Page in Latest Post mode). 

In fact, do the Home Page Areas widgets (first, second, third and forth on this theme) work at all on this theme?
 
Ideally the minimum I would like the Home Page to feature is an Image Splash, a text area to explain what we do, Latest FIVE Posts and search box. 

Kind regards

Tabitha
